package com.github.admin.module;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   账户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account
 */
public class Account {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-01-16T11:53:10.933+08:00", comments="Source field: account.id")
    private Integer id;

    /**
     * Database Column Remarks:
     *   登录名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-01-16T11:53:10.938+08:00", comments="Source field: account.name")
    private String name;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-01-16T11:53:10.938+08:00", comments="Source field: account.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-01-16T11:53:10.938+08:00", comments="Source field: account.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-01-16T11:53:10.938+08:00", comments="Source field: account.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-01-16T11:53:10.938+08:00", comments="Source field: account.name")
    public void setName(String name) {
        this.name = name;
    }
}