server:
  port: 80
  address: 0.0.0.0

spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    org.apache.mapper: debug